name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: Check Zig code formatting
      run: zig build fmt-check

    - name: Check Rust code formatting
      run: cd rust-crypto && cargo fmt -- --check

    - name: Run unit tests (includes smoke test)
      run: zig build test